# If using AWS Control Tower, ensure that all the specified Organizational Units (OU)
# have been created and enrolled as the accelerator will verify that the OU layout
# matches before continuing to execute the deployment pipeline.

enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
  - name: Central
  - name: Dev
  - name: Test
  - name: Prod
  - name: UnClass
  - name: Sandbox
quarantineNewAccounts:
  enable: true
  scpPolicyName: AWSAccelerator-Quarantine-New-Object
serviceControlPolicies:
  - name: AWSAccelerator-Guardrails-Part-0
    description: >
      LZA Guardrails Part 0 Workload Accounts
    policy: service-control-policies/LZA-Guardrails-Part0-WkldOUs.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Central
        - Dev
        - Test
        - Prod
        - UnClass
        - Sandbox
  - name: AWSAccelerator-Guardrails-Part-1
    description: >
      LZA Guardrails Part 1
    policy: service-control-policies/LZA-Guardrails-Part1.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Security
        - Infrastructure
        - Central
        - Dev
        - Test
        - Prod
        - UnClass
        - Sandbox
  ## IF using Control Tower, remove the following block and uncomment the next block
  ## BEGIN
  - name: AWSAccelerator-Guardrails-Sensitive-Part-1
    description: >
      LZA Guardrails Sensitive Environment Specific Part 1
    policy: service-control-policies/LZA-Guardrails-Sensitive.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Security
        - Infrastructure
        - Central
        - Dev
        - Test
        - Prod
  ## END
  ## IF using Control Tower, uncomment the following block
  #  - name: AWSAccelerator-Guardrails-Sensitive-Part-1
  #    description: >
  #      LZA Guardrails Sensitive Environment Specific Part 1
  #    policy: service-control-policies/LZA-Guardrails-Sensitive.json
  #    type: customerManaged
  #    deploymentTargets:
  #      organizationalUnits:
  #      - Infrastructure
  #      - Central
  #      - Dev
  #      - Test
  #      - Prod
  #      accounts:
  #      - Audit
  #      - LogArchive
  ## END
  - name: "{{ AcceleratorPrefix }}-Guardrails-Unclass"
    description: >
      LZA Guardrails Unclassified Environment Specific
    policy: service-control-policies/LZA-Guardrails-Unclass.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - UnClass
  - name: "{{ AcceleratorPrefix }}-Guardrails-Sandbox"
    description: >
      LZA Guardrails Sandbox Environment Specific
    policy: service-control-policies/LZA-Guardrails-Sandbox.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Sandbox
  - name: "{{ AcceleratorPrefix }}-Quarantine-New-Object"
    description: >
      LZA Quarantine policy - Apply to ACCOUNTS that need to be quarantined
    policy: service-control-policies/Quarantine-New-Object.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits: []
  - name: "{{ AcceleratorPrefix }}-Guardrails-Part-0-Core"
    description: >
      LZA Guardrails Part 0 Core Accounts
    policy: service-control-policies/LZA-Guardrails-Part0-CoreOUs.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Security
        - Infrastructure
taggingPolicies:
  # AWS Organizations Tagging Policies
  # - Enables tag policy for values of backup plans only
  # - This will only enforce the tag value specified matches one of the backup plans
  #   - Redshift, RDS, Timestream, DocumentDB, Neptune cannot currently be enforced
  #   - VMWare VMs are outside of scope for tag enforcement
  - name: OrgTagPolicy
    description: Organization Tagging Policy
    policy: tagging-policies/org-tag-policy.json
    deploymentTargets:
      organizationalUnits:
        - Security
        - Infrastructure
        - Central
        - Dev
        - Test
        - Prod
  # AWS Backup continuous backup is only supported for S3 & RDS but RDS isn't supported by tag policies.
  #   - https://docs.aws.amazon.com/aws-backup/latest/devguide/point-in-time-recovery.html
  - name: S3TagPolicy
    description: S3 Tagging Policy
    policy: tagging-policies/s3-tag-policy.json
    deploymentTargets:
      organizationalUnits:
        - Security
        - Infrastructure
        - Central
        - Dev
        - Test
        - Prod
backupPolicies:
  # AWS Backup Configuration
  # https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_backup.html
  # Syntax: https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_backup_syntax.html?icmpid=docs_orgs_console
  # - Retention is set for 1 year
  #   - Continuous is set to max of 35 days
  #   - Monthly is set for two years
  # - VSS Enabled (Windows) for all plans
  #   - https://docs.aws.amazon.com/aws-backup/latest/devguide/windows-backups.html
  # - Available Backup Plans
  #   - Continuous
  #   - Hourly
  #   - Daily
  #   - Weekly
  #   - Monthly
  # - Backup Window
  #   - Set to AWS Backup default of 5am UTC
  # - Tag policy with list of backup plans has been created for you, if changes in policies are made you should also update this tag policy too
  - name: "{{ AcceleratorPrefix }}-BackupPolicy"
    description: Organization Backup Policy
    policy: backup-policies/primary-backup-plan.json
    deploymentTargets:
      organizationalUnits:
        - Security
        - Infrastructure
        - Central
        - Dev
        - Test
        - Prod
